# Generated by Django 4.2.7 on 2026-05-17 07:42

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sectors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('name', models.CharField(help_text='Business name (e.g., Poultry Farming - Broilers)', max_length=200)),
                ('short_description', models.CharField(blank=True, help_text='Short tagline for cards and listings', max_length=200)),
                ('overview', models.TextField(help_text='2-3 paragraph explanation of what this business does day-to-day')),
                ('opportunity_thesis', models.TextField(help_text='Why this business makes sense in The Gambia today')),
                ('featured_image', models.ImageField(blank=True, help_text='Main image for the business', null=True, upload_to='businesses/')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', help_text='Publication status', max_length=20)),
                ('is_featured', models.BooleanField(default=False, help_text='Display on homepage and featured sections')),
                ('view_count', models.PositiveIntegerField(default=0, help_text='Number of times this business has been viewed')),
                ('sector', models.ForeignKey(help_text='Sector this business belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='businesses', to='sectors.sector')),
            ],
            options={
                'verbose_name': 'Business',
                'verbose_name_plural': 'Businesses',
                'db_table': 'businesses',
                'ordering': ['-is_featured', 'name'],
            },
        ),
        migrations.CreateModel(
            name='BusinessScale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scale_type', models.CharField(choices=[('small', 'Small Scale'), ('medium', 'Medium Scale'), ('large', 'Large Scale')], help_text='Small, Medium, or Large scale', max_length=20)),
                ('capacity_definition', models.CharField(help_text="e.g., '100-300 birds', '1-3 vehicles', '50-100 students'", max_length=200)),
                ('target_market', models.TextField(help_text='Who buys from this scale (e.g., local households, restaurants)')),
                ('location_type', models.CharField(help_text='Where it operates (e.g., backyard, peri-urban, rural commercial)', max_length=100)),
                ('labor_needed', models.CharField(help_text="Staff requirements (e.g., '1 part-time', '3+ employees')", max_length=100)),
                ('overall_feasibility_score', models.DecimalField(blank=True, decimal_places=1, help_text='Overall feasibility score out of 10', max_digits=3, null=True)),
                ('last_updated', models.DateField(auto_now=True, help_text='Date when this scale data was last updated')),
                ('business', models.ForeignKey(help_text='Business this scale belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='scales', to='businesses.business')),
            ],
            options={
                'verbose_name': 'Business Scale',
                'verbose_name_plural': 'Business Scales',
                'db_table': 'business_scales',
                'ordering': ['business', 'scale_type'],
                'unique_together': {('business', 'scale_type')},
            },
        ),
        migrations.CreateModel(
            name='Risk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('market', 'Market Risk'), ('operational', 'Operational Risk'), ('financial', 'Financial Risk'), ('regulatory', 'Regulatory Risk'), ('external', 'External Risk')], help_text='Risk category', max_length=50)),
                ('specific_risk', models.CharField(help_text='Description of the specific risk', max_length=200)),
                ('likelihood', models.PositiveSmallIntegerField(help_text='Likelihood (1=Very Low, 5=Very High)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('impact', models.PositiveSmallIntegerField(help_text='Impact (1=Very Low, 5=Very High)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('risk_score', models.PositiveSmallIntegerField(editable=False, help_text='Likelihood × Impact (auto-calculated)')),
                ('mitigation_strategy', models.TextField(help_text='How to mitigate this risk')),
                ('last_updated', models.DateField(auto_now=True, help_text='Date when this risk was last updated')),
                ('scale', models.ForeignKey(help_text='Business scale these risks apply to', on_delete=django.db.models.deletion.CASCADE, related_name='risks', to='businesses.businessscale')),
            ],
            options={
                'verbose_name': 'Risk',
                'verbose_name_plural': 'Risks',
                'db_table': 'risks',
                'ordering': ['scale', '-risk_score'],
            },
        ),
        migrations.CreateModel(
            name='OperationsChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scale_type', models.CharField(choices=[('small', 'Small Scale'), ('medium', 'Medium Scale'), ('large', 'Large Scale')], help_text="Which scale this checklist applies to (or 'all')", max_length=20)),
                ('task_type', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], help_text='Frequency of the task', max_length=20)),
                ('task_name', models.CharField(help_text='Name of the task', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Detailed description of how to perform the task')),
                ('time_of_day', models.CharField(blank=True, help_text="For daily tasks: e.g., 'Morning', 'Midday', 'Evening'", max_length=50)),
                ('responsible', models.CharField(blank=True, help_text='Who typically performs this task', max_length=100)),
                ('duration_minutes', models.PositiveSmallIntegerField(blank=True, help_text='Estimated time to complete in minutes', null=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order')),
                ('business', models.ForeignKey(help_text='Business this checklist belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='checklists', to='businesses.business')),
            ],
            options={
                'verbose_name': 'Operations Checklist',
                'verbose_name_plural': 'Operations Checklists',
                'db_table': 'operations_checklists',
                'ordering': ['business', 'scale_type', 'task_type', 'order'],
            },
        ),
        migrations.CreateModel(
            name='CapitalItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('registration', 'Registration & Legal'), ('premises', 'Premises & Housing'), ('equipment', 'Equipment & Tools'), ('inventory', 'Initial Inventory')], help_text='Category of capital expense', max_length=50)),
                ('item_name', models.CharField(help_text="Name of the item (e.g., 'Day-old Chicks', 'Poultry House')", max_length=200)),
                ('quantity', models.PositiveIntegerField(default=1, help_text='Number of units needed')),
                ('unit_cost', models.PositiveIntegerField(help_text='Cost per unit in Dalasi')),
                ('total_cost', models.PositiveIntegerField(editable=False, help_text='Quantity × Unit Cost (auto-calculated)')),
                ('priority', models.CharField(choices=[('essential', 'Essential'), ('medium', 'Medium Priority'), ('optional', 'Optional')], default='essential', help_text='How essential this item is', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Additional information or where to buy')),
                ('scale', models.ForeignKey(help_text='Business scale these costs apply to', on_delete=django.db.models.deletion.CASCADE, related_name='capital_items', to='businesses.businessscale')),
            ],
            options={
                'verbose_name': 'Capital Item',
                'verbose_name_plural': 'Capital Items',
                'db_table': 'capital_items',
                'ordering': ['scale', 'category', 'priority', 'item_name'],
            },
        ),
        migrations.CreateModel(
            name='RevenueProjection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cycle_number', models.PositiveSmallIntegerField(help_text='Production cycle number (1, 2, 3, etc.)')),
                ('unit_sales', models.PositiveIntegerField(help_text='Number of units sold in this cycle')),
                ('price_per_unit', models.PositiveIntegerField(help_text='Price per unit in Dalasi')),
                ('total_revenue', models.PositiveIntegerField(editable=False, help_text='Unit Sales × Price per Unit (auto-calculated)')),
                ('cost_of_goods', models.PositiveIntegerField(help_text='Cost of goods sold for this cycle')),
                ('gross_profit', models.PositiveIntegerField(editable=False, help_text='Total Revenue - COGS (auto-calculated)')),
                ('operating_expenses', models.PositiveIntegerField(help_text='Fixed overheads for this cycle')),
                ('net_profit', models.PositiveIntegerField(editable=False, help_text='Gross Profit - Operating Expenses (auto-calculated)')),
                ('cumulative_cash_flow', models.IntegerField(editable=False, help_text='Running total of net profits (auto-calculated)')),
                ('scale', models.ForeignKey(help_text='Business scale these projections apply to', on_delete=django.db.models.deletion.CASCADE, related_name='revenue_projections', to='businesses.businessscale')),
            ],
            options={
                'verbose_name': 'Revenue Projection',
                'verbose_name_plural': 'Revenue Projections',
                'db_table': 'revenue_projections',
                'ordering': ['scale', 'cycle_number'],
                'unique_together': {('scale', 'cycle_number')},
            },
        ),
        migrations.CreateModel(
            name='OperatingCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_range', models.CharField(help_text="Week range (e.g., '1-2', '3-4', '5-6', '7-8')", max_length=20)),
                ('feed_starter', models.PositiveIntegerField(default=0, help_text='Cost of starter feed (if applicable)')),
                ('feed_grower', models.PositiveIntegerField(default=0, help_text='Cost of grower feed (if applicable)')),
                ('feed_finisher', models.PositiveIntegerField(default=0, help_text='Cost of finisher feed (if applicable)')),
                ('utilities', models.PositiveIntegerField(default=0, help_text='Electricity, water, etc.')),
                ('water', models.PositiveIntegerField(default=0, help_text='Water costs')),
                ('medication', models.PositiveIntegerField(default=0, help_text='Medication, vaccines, etc.')),
                ('labor', models.PositiveIntegerField(default=0, help_text='Staff wages')),
                ('transport_misc', models.PositiveIntegerField(default=0, help_text='Transportation and miscellaneous costs')),
                ('total', models.PositiveIntegerField(editable=False, help_text='Sum of all costs (auto-calculated)')),
                ('scale', models.ForeignKey(help_text='Business scale these costs apply to', on_delete=django.db.models.deletion.CASCADE, related_name='operating_costs', to='businesses.businessscale')),
            ],
            options={
                'verbose_name': 'Operating Cost',
                'verbose_name_plural': 'Operating Costs',
                'db_table': 'operating_costs',
                'ordering': ['scale', 'week_range'],
                'unique_together': {('scale', 'week_range')},
            },
        ),
        migrations.CreateModel(
            name='FinancialMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breakeven_cycles', models.DecimalField(decimal_places=1, help_text='Number of cycles to break even', max_digits=4)),
                ('gross_margin_percent', models.DecimalField(decimal_places=2, help_text='Gross margin percentage', max_digits=5)),
                ('net_margin_percent', models.DecimalField(decimal_places=2, help_text='Net margin percentage', max_digits=5)),
                ('roi_percent', models.DecimalField(decimal_places=2, help_text='Return on Investment percentage', max_digits=6)),
                ('payback_months', models.DecimalField(decimal_places=1, help_text='Payback period in months', max_digits=4)),
                ('data_source', models.CharField(help_text="Source of this data (e.g., 'Field Survey 2024', 'GBoS 2024')", max_length=200)),
                ('last_updated', models.DateField(auto_now=True, help_text='Date when this data was last updated')),
                ('scale', models.ForeignKey(help_text='Business scale these metrics apply to', on_delete=django.db.models.deletion.CASCADE, related_name='financial_metrics', to='businesses.businessscale')),
            ],
            options={
                'verbose_name': 'Financial Metric',
                'verbose_name_plural': 'Financial Metrics',
                'db_table': 'financial_metrics',
                'unique_together': {('scale', 'data_source')},
            },
        ),
        migrations.CreateModel(
            name='FeasibilityFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('market', 'Market Analysis'), ('capital', 'Capital Requirements'), ('profitability', 'Profitability'), ('regulatory', 'Regulatory'), ('risk', 'Risk Assessment'), ('skills', 'Skills Required'), ('supply_chain', 'Supply Chain')], help_text='Feasibility category', max_length=50)),
                ('sub_category', models.CharField(help_text="Specific factor (e.g., 'Market Size', 'Startup Capital')", max_length=100)),
                ('rating', models.PositiveSmallIntegerField(help_text='Rating out of 10 (1=Poor, 10=Excellent)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('notes', models.TextField(blank=True, help_text='Additional context about this rating')),
                ('data_source', models.CharField(help_text="Source of this data (e.g., 'GBoS 2024', 'Field Survey')", max_length=200)),
                ('last_updated', models.DateField(auto_now=True, help_text='Date when this factor was last updated')),
                ('scale', models.ForeignKey(help_text='Business scale these factors apply to', on_delete=django.db.models.deletion.CASCADE, related_name='feasibility_factors', to='businesses.businessscale')),
            ],
            options={
                'verbose_name': 'Feasibility Factor',
                'verbose_name_plural': 'Feasibility Factors',
                'db_table': 'feasibility_factors',
                'ordering': ['scale', 'category', 'sub_category'],
                'unique_together': {('scale', 'category', 'sub_category')},
            },
        ),
        migrations.AddIndex(
            model_name='business',
            index=models.Index(fields=['slug'], name='businesses_slug_279d6a_idx'),
        ),
        migrations.AddIndex(
            model_name='business',
            index=models.Index(fields=['sector', 'status'], name='businesses_sector__dd18a7_idx'),
        ),
        migrations.AddIndex(
            model_name='business',
            index=models.Index(fields=['is_featured'], name='businesses_is_feat_37b704_idx'),
        ),
    ]
