# Generated by Django 4.2.7 on 2026-05-17 09:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sectors', '0001_initial'),
        ('businesses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('name', models.CharField(help_text='Business name', max_length=200)),
                ('owner_name', models.CharField(blank=True, help_text='Owner or founder name', max_length=200)),
                ('owner_position', models.CharField(blank=True, help_text='Owner position (e.g., Founder, CEO, Managing Director)', max_length=100)),
                ('description', models.TextField(help_text='Business description')),
                ('short_description', models.CharField(blank=True, help_text='Short description for listings', max_length=200)),
                ('logo', models.ImageField(blank=True, help_text='Business logo', null=True, upload_to='business-profiles/logos/')),
                ('cover_image', models.ImageField(blank=True, help_text='Cover/banner image', null=True, upload_to='business-profiles/covers/')),
                ('email', models.EmailField(blank=True, help_text='Business email', max_length=254)),
                ('phone', models.CharField(blank=True, help_text='Business phone number', max_length=50)),
                ('website', models.URLField(blank=True, help_text='Business website')),
                ('address', models.TextField(blank=True, help_text='Physical address')),
                ('location', models.CharField(blank=True, help_text='City/region (e.g., Banjul, Serrekunda)', max_length=200)),
                ('facebook', models.URLField(blank=True, help_text='Facebook page URL')),
                ('instagram', models.URLField(blank=True, help_text='Instagram handle or URL')),
                ('linkedin', models.URLField(blank=True, help_text='LinkedIn company page URL')),
                ('twitter', models.URLField(blank=True, help_text='Twitter/X handle or URL')),
                ('tiktok', models.URLField(blank=True, help_text='TikTok handle or URL')),
                ('whatsapp', models.CharField(blank=True, help_text='WhatsApp number', max_length=50)),
                ('founded_year', models.PositiveSmallIntegerField(blank=True, help_text='Year the business was founded', null=True)),
                ('employee_count', models.CharField(blank=True, help_text="Number of employees (e.g., '1-5', '10-50')", max_length=50)),
                ('business_type', models.CharField(blank=True, help_text="Business type (e.g., 'Sole Proprietorship', 'LLC')", max_length=100)),
                ('is_partner', models.BooleanField(default=False, help_text='Is this a trusted partner/service provider')),
                ('is_featured', models.BooleanField(default=False, help_text='Display on homepage and featured sections')),
                ('is_verified', models.BooleanField(default=False, help_text='Has this business been verified by GBI team')),
                ('partner_type', models.CharField(blank=True, help_text='If partner: consultant, supplier, legal, etc.', max_length=50)),
                ('interview_date', models.DateField(blank=True, help_text='Date when interview was conducted', null=True)),
                ('interviewed_by', models.CharField(default='Ebrima Barry', help_text='Name of interviewer', max_length=100)),
                ('interview_notes', models.TextField(blank=True, help_text='Internal notes about the interview')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='published', help_text='Publication status', max_length=20)),
                ('view_count', models.PositiveIntegerField(default=0, help_text='Number of profile views')),
                ('sector', models.ForeignKey(blank=True, help_text='Primary sector', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='business_profiles', to='sectors.sector')),
                ('user', models.OneToOneField(blank=True, help_text='Linked user account (if business wants to manage their profile)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='business_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Business Profile',
                'verbose_name_plural': 'Business Profiles',
                'db_table': 'business_profiles',
                'ordering': ['-is_featured', '-is_verified', 'name'],
            },
        ),
        migrations.CreateModel(
            name='BusinessProfileTestimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('quote', models.TextField(help_text='The testimonial quote')),
                ('author_name', models.CharField(help_text='Name of person giving testimonial', max_length=100)),
                ('author_position', models.CharField(blank=True, help_text="Position of author (e.g., 'Founder')", max_length=100)),
                ('is_featured', models.BooleanField(default=False, help_text='Display on homepage')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order')),
                ('business_profile', models.ForeignKey(help_text='Business profile this testimonial belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='testimonials', to='businesses.businessprofile')),
            ],
            options={
                'verbose_name': 'Business Profile Testimonial',
                'verbose_name_plural': 'Business Profile Testimonials',
                'db_table': 'business_profile_testimonials',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='BusinessProfileFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('title', models.CharField(help_text="Feature title (e.g., '25% Revenue Growth')", max_length=200)),
                ('description', models.TextField(help_text='Feature description')),
                ('icon', models.CharField(blank=True, help_text="Icon name (e.g., 'TrendingUp', 'Users')", max_length=50)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order')),
                ('business_profile', models.ForeignKey(help_text='Business profile this feature belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='features', to='businesses.businessprofile')),
            ],
            options={
                'verbose_name': 'Business Profile Feature',
                'verbose_name_plural': 'Business Profile Features',
                'db_table': 'business_profile_features',
                'ordering': ['order'],
            },
        ),
        migrations.AddIndex(
            model_name='businessprofile',
            index=models.Index(fields=['slug'], name='business_pr_slug_69dc30_idx'),
        ),
        migrations.AddIndex(
            model_name='businessprofile',
            index=models.Index(fields=['is_partner', 'is_verified'], name='business_pr_is_part_1325aa_idx'),
        ),
        migrations.AddIndex(
            model_name='businessprofile',
            index=models.Index(fields=['sector'], name='business_pr_sector__1bf552_idx'),
        ),
        migrations.AddIndex(
            model_name='businessprofile',
            index=models.Index(fields=['location'], name='business_pr_locatio_4ebb59_idx'),
        ),
    ]
