# Generated by Django 4.2.7 on 2026-05-25 10:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('businesses', '0001_initial'),
        ('sectors', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessprofile',
            name='user',
            field=models.OneToOneField(blank=True, help_text='Linked user account for future self-service profile management', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='business_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='business',
            name='sector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='businesses', to='sectors.sector'),
        ),
        migrations.AddIndex(
            model_name='timeseriesmetric',
            index=models.Index(fields=['business', 'metric_name', 'year'], name='time_series_busines_d6fbff_idx'),
        ),
        migrations.AddIndex(
            model_name='timeseriesmetric',
            index=models.Index(fields=['year', 'scale_type', 'metric_name'], name='time_series_year_e6e1a4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='timeseriesmetric',
            unique_together={('business', 'scale_type', 'metric_name', 'year')},
        ),
        migrations.AddIndex(
            model_name='risk',
            index=models.Index(fields=['scale', 'risk_score'], name='risks_scale_i_6fac39_idx'),
        ),
        migrations.AddIndex(
            model_name='revenueprojection',
            index=models.Index(fields=['scale', 'period_number', 'period_type'], name='revenue_pro_scale_i_7ede9f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='revenueprojection',
            unique_together={('scale', 'period_number', 'period_type')},
        ),
        migrations.AddIndex(
            model_name='operatingcost',
            index=models.Index(fields=['scale', 'period_number', 'period_type'], name='operating_c_scale_i_7f825e_idx'),
        ),
        migrations.AddIndex(
            model_name='operatingcost',
            index=models.Index(fields=['cost_category'], name='operating_c_cost_ca_076d5c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='operatingcost',
            unique_together={('scale', 'period_number', 'period_type', 'cost_category')},
        ),
        migrations.AddIndex(
            model_name='intelligencesnapshot',
            index=models.Index(fields=['year', 'scale_type', 'status', 'is_latest'], name='intelligenc_year_0fae3b_idx'),
        ),
        migrations.AddIndex(
            model_name='intelligencesnapshot',
            index=models.Index(fields=['sector_id', 'year', 'status'], name='intelligenc_sector__bd1437_idx'),
        ),
        migrations.AddIndex(
            model_name='intelligencesnapshot',
            index=models.Index(fields=['startup_cost', 'payback_months'], name='intelligenc_startup_e46e77_idx'),
        ),
        migrations.AddIndex(
            model_name='intelligencesnapshot',
            index=models.Index(fields=['gross_margin_pct', 'feasibility_score'], name='intelligenc_gross_m_f405db_idx'),
        ),
        migrations.AddIndex(
            model_name='intelligencesnapshot',
            index=models.Index(fields=['min_investment', 'max_investment'], name='intelligenc_min_inv_8e054e_idx'),
        ),
        migrations.AddIndex(
            model_name='intelligencesnapshot',
            index=models.Index(fields=['is_latest', 'status', 'published_at'], name='intelligenc_is_late_d880ae_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='intelligencesnapshot',
            unique_together={('business', 'scale_type', 'year', 'version')},
        ),
        migrations.AddIndex(
            model_name='financialmetric',
            index=models.Index(fields=['scale', 'is_primary'], name='financial_m_scale_i_6aecbb_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='feasibilityfactor',
            unique_together={('scale', 'category', 'sub_category')},
        ),
        migrations.AddIndex(
            model_name='capitalitem',
            index=models.Index(fields=['scale', 'category'], name='capital_ite_scale_i_9e5e50_idx'),
        ),
        migrations.AddIndex(
            model_name='businessscale',
            index=models.Index(fields=['business', 'year', 'scale_type'], name='business_sc_busines_51857b_idx'),
        ),
        migrations.AddIndex(
            model_name='businessscale',
            index=models.Index(fields=['year', 'scale_type'], name='business_sc_year_a7acd8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='businessscale',
            unique_together={('business', 'scale_type', 'year')},
        ),
        migrations.AddIndex(
            model_name='businessprofile',
            index=models.Index(fields=['slug'], name='business_pr_slug_69dc30_idx'),
        ),
        migrations.AddIndex(
            model_name='businessprofile',
            index=models.Index(fields=['is_partner', 'is_verified'], name='business_pr_is_part_1325aa_idx'),
        ),
        migrations.AddIndex(
            model_name='businessprofile',
            index=models.Index(fields=['sector'], name='business_pr_sector__1bf552_idx'),
        ),
        migrations.AddIndex(
            model_name='businessprofile',
            index=models.Index(fields=['location'], name='business_pr_locatio_4ebb59_idx'),
        ),
        migrations.AddIndex(
            model_name='businessprofile',
            index=models.Index(fields=['status'], name='business_pr_status_26af36_idx'),
        ),
        migrations.AddIndex(
            model_name='businessprofile',
            index=models.Index(fields=['business_type'], name='business_pr_busines_21a552_idx'),
        ),
        migrations.AddIndex(
            model_name='business',
            index=models.Index(fields=['slug'], name='businesses_slug_279d6a_idx'),
        ),
        migrations.AddIndex(
            model_name='business',
            index=models.Index(fields=['sector', 'status'], name='businesses_sector__dd18a7_idx'),
        ),
        migrations.AddIndex(
            model_name='business',
            index=models.Index(fields=['is_featured'], name='businesses_is_feat_37b704_idx'),
        ),
        migrations.AddIndex(
            model_name='business',
            index=models.Index(fields=['status'], name='businesses_status_7e9830_idx'),
        ),
        migrations.AddIndex(
            model_name='business',
            index=models.Index(fields=['has_scales'], name='businesses_has_sca_b88197_idx'),
        ),
    ]
