# Generated by Django 4.2.7 on 2026-05-17 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0002_businessprofile_businessprofiletestimonial_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businessprofilefeature',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='businessprofilefeature',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='businessprofilefeature',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='businessprofiletestimonial',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='businessprofiletestimonial',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='businessprofiletestimonial',
            name='slug',
        ),
    ]
