# Generated by Django 4.2.7 on 2026-05-29 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('review', 'Under Review'), ('published', 'Published'), ('archived', 'Archived')], db_index=True, default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='businessprofile',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('review', 'Under Review'), ('published', 'Published'), ('archived', 'Archived')], db_index=True, default='published', max_length=20),
        ),
        migrations.AlterField(
            model_name='capitalitem',
            name='priority',
            field=models.CharField(choices=[('essential', 'Essential'), ('recommended', 'Recommended'), ('optional', 'Optional')], default='essential', max_length=20),
        ),
        migrations.AlterField(
            model_name='feasibilityfactor',
            name='category',
            field=models.CharField(choices=[('market', 'Market Analysis'), ('financial', 'Financial Viability'), ('operations', 'Operational Capacity'), ('regulatory', 'Regulatory Environment'), ('technical', 'Technical Requirements'), ('competitive', 'Competitive Landscape')], max_length=30),
        ),
        migrations.AlterField(
            model_name='risk',
            name='category',
            field=models.CharField(choices=[('market', 'Market Risk'), ('operational', 'Operational Risk'), ('financial', 'Financial Risk'), ('regulatory', 'Regulatory Risk'), ('supply', 'Supply Chain Risk'), ('climate', 'Climate / Environmental Risk'), ('competitive', 'Competitive Risk'), ('technological', 'Technological Risk')], max_length=30),
        ),
    ]
