# Generated by Django 4.2.7 on 2026-05-20 19:28

import apps.businesses.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0003_remove_businessprofilefeature_deleted_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessprofilefeature',
            name='cover_image',
            field=models.ImageField(blank=True, help_text='Cover/banner image', null=True, upload_to=apps.businesses.models.business_profile_cover_path),
        ),
        migrations.AddField(
            model_name='businessprofilefeature',
            name='logo',
            field=models.ImageField(blank=True, help_text='Business logo', null=True, upload_to=apps.businesses.models.business_profile_logo_path),
        ),
        migrations.AlterField(
            model_name='business',
            name='featured_image',
            field=models.ImageField(blank=True, help_text='Main image for the business', null=True, upload_to=apps.businesses.models.business_image_path),
        ),
    ]
