# Generated by Django 4.2.7 on 2026-05-17 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sectors', '0001_initial'),
        ('businesses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('title', models.CharField(help_text='Article title', max_length=200)),
                ('excerpt', models.CharField(help_text='Short summary displayed in listings', max_length=300)),
                ('content', models.TextField(help_text='Full article content (HTML or Markdown)')),
                ('premium_content', models.TextField(blank=True, help_text='Premium-only content (shown only to subscribers)')),
                ('featured_image', models.ImageField(blank=True, help_text='Main image for the article', null=True, upload_to='articles/')),
                ('author', models.CharField(default='GBI Research Team', help_text='Author name', max_length=100)),
                ('read_time', models.PositiveSmallIntegerField(default=5, help_text='Estimated read time in minutes')),
                ('is_premium', models.BooleanField(default=False, help_text='Whether this article requires premium subscription')),
                ('is_featured', models.BooleanField(default=False, help_text='Display on homepage and featured sections')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', help_text='Publication status', max_length=20)),
                ('published_at', models.DateTimeField(blank=True, help_text='When the article was published', null=True)),
                ('view_count', models.PositiveIntegerField(default=0, help_text='Number of views')),
                ('like_count', models.PositiveIntegerField(default=0, help_text='Number of likes')),
                ('meta_title', models.CharField(blank=True, help_text='SEO title (defaults to article title)', max_length=150)),
                ('meta_description', models.CharField(blank=True, help_text='SEO description', max_length=300)),
                ('business', models.ForeignKey(blank=True, help_text='Specific business this article is about', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='businesses.business')),
                ('sector', models.ForeignKey(blank=True, help_text='Primary sector this article belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='sectors.sector')),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
                'db_table': 'articles',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CaseStudy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('title', models.CharField(help_text='Case study title', max_length=200)),
                ('excerpt', models.CharField(help_text='Short summary', max_length=300)),
                ('content', models.TextField(help_text='Full case study content')),
                ('featured_image', models.ImageField(blank=True, help_text='Main image', null=True, upload_to='case-studies/')),
                ('business_name', models.CharField(help_text='Name of the business being studied', max_length=200)),
                ('business_type', models.CharField(help_text='Type of business (e.g., Poultry Farm, Taxi Service)', max_length=100)),
                ('initial_investment', models.PositiveIntegerField(blank=True, help_text='Initial investment amount in Dalasi', null=True)),
                ('revenue_generated', models.PositiveIntegerField(blank=True, help_text='Revenue generated in Dalasi', null=True)),
                ('roi_percent', models.DecimalField(blank=True, decimal_places=2, help_text='Return on investment percentage', max_digits=6, null=True)),
                ('timeline_months', models.PositiveSmallIntegerField(blank=True, help_text='Timeline in months to achieve results', null=True)),
                ('is_success', models.BooleanField(default=True, help_text='Whether this is a success story (True) or failure (False)')),
                ('key_lessons', models.TextField(help_text='Key takeaways and lessons learned')),
                ('author', models.CharField(default='GBI Research Team', help_text='Author name', max_length=100)),
                ('is_featured', models.BooleanField(default=False, help_text='Display on homepage and featured sections')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', help_text='Publication status', max_length=20)),
                ('published_at', models.DateTimeField(blank=True, help_text='When the case study was published', null=True)),
                ('view_count', models.PositiveIntegerField(default=0, help_text='Number of views')),
                ('sector', models.ForeignKey(blank=True, help_text='Sector this case study belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='case_studies', to='sectors.sector')),
            ],
            options={
                'verbose_name': 'Case Study',
                'verbose_name_plural': 'Case Studies',
                'db_table': 'case_studies',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('title', models.CharField(help_text='Video title', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Video description')),
                ('platform', models.CharField(choices=[('youtube', 'YouTube'), ('tiktok', 'TikTok'), ('vimeo', 'Vimeo')], default='youtube', help_text='Video platform', max_length=20)),
                ('platform_video_id', models.CharField(help_text='Video ID from the platform (e.g., YouTube video ID)', max_length=100)),
                ('video_url', models.URLField(blank=True, help_text='Full video URL (auto-generated from platform and ID)')),
                ('thumbnail_url', models.URLField(blank=True, help_text='Thumbnail image URL')),
                ('duration', models.PositiveSmallIntegerField(blank=True, help_text='Duration in seconds', null=True)),
                ('is_premium', models.BooleanField(default=False, help_text='Whether this video requires premium subscription')),
                ('is_featured', models.BooleanField(default=False, help_text='Display on homepage and featured sections')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='published', help_text='Publication status', max_length=20)),
                ('published_at', models.DateTimeField(blank=True, help_text='When the video was published', null=True)),
                ('view_count', models.PositiveIntegerField(default=0, help_text='Number of views')),
                ('like_count', models.PositiveIntegerField(default=0, help_text='Number of likes')),
                ('comment_count', models.PositiveIntegerField(default=0, help_text='Number of comments')),
                ('business', models.ForeignKey(blank=True, help_text='Specific business this video is about', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='videos', to='businesses.business')),
                ('sector', models.ForeignKey(blank=True, help_text='Primary sector this video belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='videos', to='sectors.sector')),
            ],
            options={
                'verbose_name': 'Video',
                'verbose_name_plural': 'Videos',
                'db_table': 'videos',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('name', models.CharField(help_text="Tag name (e.g., 'Startup Tips', 'Investment')", max_length=50, unique=True)),
                ('usage_count', models.PositiveIntegerField(default=0, help_text='Number of times this tag is used (auto-updated)')),
                ('articles', models.ManyToManyField(blank=True, help_text='Articles with this tag', related_name='tags', to='content.article')),
                ('case_studies', models.ManyToManyField(blank=True, help_text='Case studies with this tag', related_name='tags', to='content.casestudy')),
                ('videos', models.ManyToManyField(blank=True, help_text='Videos with this tag', related_name='tags', to='content.video')),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
                'db_table': 'tags',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('user_name', models.CharField(help_text="Commenter's name", max_length=100)),
                ('user_email', models.EmailField(help_text="Commenter's email", max_length=254)),
                ('content', models.TextField(help_text='Comment content')),
                ('is_approved', models.BooleanField(default=False, help_text='Whether the comment is approved for display')),
                ('like_count', models.PositiveIntegerField(default=0, help_text='Number of likes')),
                ('article', models.ForeignKey(help_text='Article this comment belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='content.article')),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comments',
                'db_table': 'comments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='video',
            index=models.Index(fields=['slug'], name='videos_slug_e86041_idx'),
        ),
        migrations.AddIndex(
            model_name='video',
            index=models.Index(fields=['status', 'published_at'], name='videos_status_08ba21_idx'),
        ),
        migrations.AddIndex(
            model_name='video',
            index=models.Index(fields=['is_featured'], name='videos_is_feat_b71896_idx'),
        ),
        migrations.AddIndex(
            model_name='video',
            index=models.Index(fields=['platform'], name='videos_platfor_6f458c_idx'),
        ),
        migrations.AddIndex(
            model_name='video',
            index=models.Index(fields=['sector'], name='videos_sector__e31511_idx'),
        ),
        migrations.AddIndex(
            model_name='video',
            index=models.Index(fields=['business'], name='videos_busines_e8dd06_idx'),
        ),
        migrations.AddIndex(
            model_name='tag',
            index=models.Index(fields=['slug'], name='tags_slug_c72f9b_idx'),
        ),
        migrations.AddIndex(
            model_name='tag',
            index=models.Index(fields=['usage_count'], name='tags_usage_c_26dec2_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['article', 'is_approved'], name='comments_article_80eb08_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['-created_at'], name='comments_created_5a6deb_idx'),
        ),
        migrations.AddIndex(
            model_name='casestudy',
            index=models.Index(fields=['slug'], name='case_studie_slug_94f095_idx'),
        ),
        migrations.AddIndex(
            model_name='casestudy',
            index=models.Index(fields=['status', 'published_at'], name='case_studie_status_1bba9c_idx'),
        ),
        migrations.AddIndex(
            model_name='casestudy',
            index=models.Index(fields=['sector'], name='case_studie_sector__daa35d_idx'),
        ),
        migrations.AddIndex(
            model_name='casestudy',
            index=models.Index(fields=['is_success'], name='case_studie_is_succ_7b5f29_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['slug'], name='articles_slug_c8b0c2_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['status', 'published_at'], name='articles_status_35ee01_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['is_featured'], name='articles_is_feat_9387e0_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['sector'], name='articles_sector__f9501d_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['business'], name='articles_busines_a2f9ee_idx'),
        ),
    ]
