# Generated by Django 4.2.7 on 2026-05-20 19:28

import apps.content.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_remove_comment_deleted_at_remove_comment_is_deleted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='featured_image',
            field=models.ImageField(blank=True, help_text='Main image for the article', null=True, upload_to=apps.content.models.article_image_path),
        ),
    ]
