# Generated by Django 4.2.7 on 2026-05-20 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_alter_article_featured_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='platform_video_id',
            field=models.CharField(blank=True, help_text='Video ID from the platform (e.g., YouTube video ID)', max_length=100),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_url',
            field=models.URLField(help_text='Full video URL (required - enter the complete URL)'),
        ),
    ]
