# Generated by Django 4.2.7 on 2026-05-25 10:38

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="Source name, e.g. 'GBoS 2024', 'Field Survey – Banjul Q1 2025'", max_length=200)),
                ('reference', models.CharField(blank=True, help_text="Specific document / table reference, e.g. 'Annual Trade Report, Table 4.2'", max_length=300)),
                ('url', models.URLField(blank=True, help_text='Link to source document if available online')),
                ('publication_date', models.DateField(blank=True, help_text='When this source was published or data was collected', null=True)),
                ('year', models.IntegerField(db_index=True, help_text='Year this source primarily applies to')),
                ('source_type', models.CharField(choices=[('government', 'Government statistics'), ('field_survey', 'Field survey'), ('interview', 'Operator interview'), ('industry', 'Industry report'), ('academic', 'Academic research'), ('internal', 'GAMBIH research'), ('projection', 'Projection / forecast')], db_index=True, default='internal', max_length=30)),
                ('confidence_rating', models.DecimalField(decimal_places=1, default=7.0, help_text='Reliability score 1.0–10.0 (10 = highest confidence)', max_digits=3, validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(10.0)])),
                ('is_primary_source', models.BooleanField(default=False, help_text='True if this is first-hand data (field interview, survey). False for secondary sources (GBoS, industry reports). Used by AI summaries to calibrate claim confidence.')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Source',
                'verbose_name_plural': 'Sources',
                'db_table': 'sources',
                'ordering': ['-year', '-confidence_rating', 'name'],
                'indexes': [models.Index(fields=['source_type', 'year'], name='sources_source__74224b_idx'), models.Index(fields=['confidence_rating'], name='sources_confide_1f1598_idx'), models.Index(fields=['year'], name='sources_year_dbacb6_idx')],
            },
        ),
        migrations.CreateModel(
            name='APIKey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('organization', models.CharField(help_text='Client organization name', max_length=200)),
                ('key', models.CharField(db_index=True, editable=False, max_length=64, unique=True)),
                ('tier', models.CharField(choices=[('free', 'Free (rate limited)'), ('premium', 'Premium'), ('pro', 'Pro'), ('enterprise', 'Enterprise (unlimited)')], default='free', max_length=20)),
                ('rate_limit_per_minute', models.IntegerField(default=60, help_text='Maximum requests per minute (0 = unlimited)')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('last_used', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('contact_name', models.CharField(blank=True, max_length=200)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'API Key',
                'verbose_name_plural': 'API Keys',
                'db_table': 'api_keys',
                'indexes': [models.Index(fields=['key', 'is_active'], name='api_keys_key_9cfb4a_idx'), models.Index(fields=['tier'], name='api_keys_tier_45581a_idx'), models.Index(fields=['expires_at'], name='api_keys_expires_f68b1a_idx')],
            },
        ),
        migrations.CreateModel(
            name='RatingValue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('value', models.DecimalField(decimal_places=1, help_text='Rating 1.0–10.0', max_digits=3, validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(10.0)])),
                ('year', models.IntegerField(db_index=True, help_text='Year this rating applies to')),
                ('confidence_score', models.DecimalField(decimal_places=1, default=7.0, max_digits=3, validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(10.0)])),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ratings', to='core.source')),
            ],
            options={
                'verbose_name': 'Rating value',
                'verbose_name_plural': 'Rating values',
                'db_table': 'ratings',
                'indexes': [models.Index(fields=['value'], name='ratings_value_2f6d17_idx'), models.Index(fields=['year'], name='ratings_year_fbc9f2_idx')],
            },
        ),
    ]
