# Generated by Django 4.2.7 on 2026-05-29 15:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('gm', 'The Gambia'), ('sn', 'Senegal'), ('gh', 'Ghana'), ('ng', 'Nigeria'), ('ci', "Côte d'Ivoire"), ('ml', 'Mali'), ('bf', 'Burkina Faso'), ('gn', 'Guinea'), ('gw', 'Guinea-Bissau'), ('sl', 'Sierra Leone'), ('lr', 'Liberia'), ('bj', 'Benin'), ('tg', 'Togo'), ('cv', 'Cape Verde'), ('ne', 'Niger'), ('mr', 'Mauritania')], db_index=True, help_text='ISO country code', max_length=2, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('flag_emoji', models.CharField(blank=True, max_length=10)),
                ('currency', models.CharField(choices=[('GMD', 'Gambian Dalasi'), ('XOF', 'West African CFA Franc'), ('GHS', 'Ghanaian Cedi'), ('NGN', 'Nigerian Naira'), ('USD', 'US Dollar'), ('GNF', 'Guinean Franc'), ('SLL', 'Sierra Leonean Leone'), ('LRD', 'Liberian Dollar'), ('CVE', 'Cape Verdean Escudo'), ('MRU', 'Mauritanian Ouguiya')], default='GMD', max_length=3)),
                ('currency_symbol', models.CharField(blank=True, max_length=5)),
                ('population', models.PositiveIntegerField(blank=True, null=True)),
                ('gdp_per_capita_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Country',
                'verbose_name_plural': 'Countries',
                'db_table': 'countries',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('west_africa', 'West Africa'), ('ecowas', 'ECOWAS (Economic Community of West African States)'), ('coastal', 'Coastal West Africa'), ('sahelian', 'Sahelian West Africa'), ('gambia_river', 'Gambia River Basin'), ('francophone', 'Francophone West Africa'), ('anglophone', 'Anglophone West Africa')], max_length=100, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Region',
                'verbose_name_plural': 'Regions',
                'db_table': 'regions',
            },
        ),
        migrations.RemoveIndex(
            model_name='apikey',
            name='api_keys_key_9cfb4a_idx',
        ),
        migrations.RemoveIndex(
            model_name='apikey',
            name='api_keys_tier_45581a_idx',
        ),
        migrations.RemoveIndex(
            model_name='apikey',
            name='api_keys_expires_f68b1a_idx',
        ),
        migrations.RemoveIndex(
            model_name='ratingvalue',
            name='ratings_value_2f6d17_idx',
        ),
        migrations.RemoveIndex(
            model_name='ratingvalue',
            name='ratings_year_fbc9f2_idx',
        ),
        migrations.RemoveIndex(
            model_name='source',
            name='sources_source__74224b_idx',
        ),
        migrations.RemoveIndex(
            model_name='source',
            name='sources_confide_1f1598_idx',
        ),
        migrations.RemoveIndex(
            model_name='source',
            name='sources_year_dbacb6_idx',
        ),
        migrations.AlterField(
            model_name='apikey',
            name='organization',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='apikey',
            name='rate_limit_per_minute',
            field=models.IntegerField(default=60),
        ),
        migrations.AlterField(
            model_name='ratingvalue',
            name='value',
            field=models.DecimalField(decimal_places=1, max_digits=3, validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(10.0)]),
        ),
        migrations.AlterField(
            model_name='ratingvalue',
            name='year',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='source',
            name='confidence_rating',
            field=models.DecimalField(decimal_places=1, default=7.0, max_digits=3, validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(10.0)]),
        ),
        migrations.AlterField(
            model_name='source',
            name='is_primary_source',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='source',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='source',
            name='publication_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='source',
            name='reference',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='source',
            name='source_type',
            field=models.CharField(choices=[('government', 'Government statistics'), ('field_survey', 'Field survey'), ('interview', 'Operator interview'), ('industry', 'Industry report'), ('academic', 'Academic research'), ('internal', 'GAMBIH research'), ('projection', 'Projection / forecast')], default='internal', max_length=30),
        ),
        migrations.AlterField(
            model_name='source',
            name='url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='source',
            name='year',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AddField(
            model_name='region',
            name='countries',
            field=models.ManyToManyField(blank=True, related_name='regions', to='core.country'),
        ),
    ]
