# apps/core/seed_data/countries.py

COUNTRIES = [
    {
        "country": "gm",
        "name": "The Gambia",
        "flag_emoji": "🇬🇲",
        "currency": "GMD",
        "currency_symbol": "D",
        "population": 2700000,
        "gdp_per_capita": 800,
        "order": 1,
        "is_active": True,
        "market_summary": "The Gambia offers opportunities in agriculture, tourism, and services. The economy is growing with increasing diaspora investment.",
    },
    {
        "country": "sn",
        "name": "Senegal",
        "flag_emoji": "🇸🇳",
        "currency": "XOF",
        "currency_symbol": "CFA",
        "population": 17000000,
        "gdp_per_capita": 1600,
        "order": 2,
        "is_active": True,
        "market_summary": "Senegal has a diversified economy with strong agriculture, fishing, mining, and services sectors. Dakar is a regional hub.",
    },
    {
        "country": "gh",
        "name": "Ghana",
        "flag_emoji": "🇬🇭",
        "currency": "GHS",
        "currency_symbol": "₵",
        "population": 31000000,
        "gdp_per_capita": 2200,
        "order": 3,
        "is_active": True,
        "market_summary": "Ghana is one of West Africa's fastest-growing economies with gold, oil, cocoa, and technology sectors.",
    },
    {
        "country": "ng",
        "name": "Nigeria",
        "flag_emoji": "🇳🇬",
        "currency": "NGN",
        "currency_symbol": "₦",
        "population": 213000000,
        "gdp_per_capita": 2100,
        "order": 4,
        "is_active": False,  # Start with Gambia, Senegal, Ghana
        "market_summary": "Nigeria is Africa's largest economy with opportunities in oil, agriculture, technology, and manufacturing.",
    },
    {
        "country": "ci",
        "name": "Côte d'Ivoire",
        "flag_emoji": "🇨🇮",
        "currency": "XOF",
        "currency_symbol": "CFA",
        "population": 26000000,
        "gdp_per_capita": 2300,
        "order": 5,
        "is_active": False,
        "market_summary": "World's largest cocoa producer with growing manufacturing and services sectors.",
    },
    {
        "country": "bf",
        "name": "Burkina Faso",
        "flag_emoji": "🇧🇫",
        "currency": "XOF",
        "currency_symbol": "CFA",
        "population": 21000000,
        "gdp_per_capita": 800,
        "order": 6,
        "is_active": False,
        "market_summary": "Agricultural economy with gold mining and cotton production.",
    },
    {
        "country": "ml",
        "name": "Mali",
        "flag_emoji": "🇲🇱",
        "currency": "XOF",
        "currency_symbol": "CFA",
        "population": 20000000,
        "gdp_per_capita": 900,
        "order": 7,
        "is_active": False,
        "market_summary": "Gold mining, agriculture, and livestock with growing opportunities.",
    },
    {
        "country": "gw",
        "name": "Guinea-Bissau",
        "flag_emoji": "🇬🇼",
        "currency": "XOF",
        "currency_symbol": "CFA",
        "population": 2000000,
        "gdp_per_capita": 800,
        "order": 8,
        "is_active": False,
        "market_summary": "Cashew nuts, fishing, and agriculture dominate the economy.",
    },
    {
        "country": "gn",
        "name": "Guinea",
        "flag_emoji": "🇬🇳",
        "currency": "GNF",
        "currency_symbol": "FG",
        "population": 13000000,
        "gdp_per_capita": 1100,
        "order": 9,
        "is_active": False,
        "market_summary": "Rich in bauxite, iron ore, and hydropower potential.",
    },
    {
        "country": "sl",
        "name": "Sierra Leone",
        "flag_emoji": "🇸🇱",
        "currency": "SLL",
        "currency_symbol": "Le",
        "population": 8000000,
        "gdp_per_capita": 500,
        "order": 10,
        "is_active": False,
        "market_summary": "Diamond mining, agriculture, and fisheries with rebuilding economy.",
    },
]

REGIONS = [
    {
        "name": "West Africa",
        "slug": "west-africa",
        "description": "All West African countries",
        "countries": ["gm", "sn", "gw", "gn", "ml", "bf", "ci", "gh", "tg", "bj", "ng", "sl", "lr", "cv"],
    },
    {
        "name": "ECOWAS",
        "slug": "ecowas",
        "description": "Economic Community of West African States",
        "countries": ["gm", "sn", "gw", "gn", "ml", "bf", "ci", "gh", "tg", "bj", "ng", "sl", "lr", "cv"],
    },
    {
        "name": "Coastal West Africa",
        "slug": "coastal",
        "description": "Coastal countries with access to the Atlantic",
        "countries": ["sn", "gw", "gn", "ci", "gh", "tg", "bj", "ng", "sl", "lr"],
    },
    {
        "name": "Sahelian West Africa",
        "slug": "sahelian",
        "description": "Sahel region countries",
        "countries": ["gm", "sn", "ml", "bf", "ng"],
    },
]