# apps/core/seed_data/reports.py

REPORTS = [
    {
        "title": "Poultry Farming - Broilers",
        "subtitle": "Complete Business Guide",
        "short_description": "Comprehensive guide to starting and running a profitable broiler poultry farm in The Gambia.",
        "description": "This detailed report covers everything from day-old chick selection to marketing finished birds. Includes capital requirements, operational costs, revenue projections, and risk assessment.",
        "report_type": "business",
        "format": "pdf",
        "price": 499,
        "is_free": False,
        "is_featured": True,
        "is_bestseller": True,
        "page_count": 45,
        "version": "2.0",
        "author": "GBI Research Team",
        "sector_name": "Agriculture",
        "business_name": "Poultry Farming - Broilers",
        "status": "published"
    },
    {
        "title": "Taxi Services",
        "subtitle": "Complete Business Guide",
        "short_description": "Complete guide to starting and operating a successful taxi business in Gambian cities.",
        "description": "This report covers vehicle selection, licensing requirements, daily operations, customer acquisition, and financial management for taxi businesses.",
        "report_type": "business",
        "format": "pdf",
        "price": 399,
        "is_free": False,
        "is_featured": True,
        "is_bestseller": False,
        "page_count": 38,
        "version": "1.5",
        "author": "GBI Research Team",
        "sector_name": "Transportation & Logistics",
        "business_name": "Taxi Services",
        "status": "published"
    },
    {
        "title": "Software Development Agency",
        "subtitle": "Complete Business Guide",
        "short_description": "Guide to starting and scaling a software development agency in The Gambia.",
        "description": "This report covers skills required, client acquisition, pricing strategies, project management, and growth strategies for tech businesses.",
        "report_type": "business",
        "format": "pdf",
        "price": 499,
        "is_free": False,
        "is_featured": True,
        "is_bestseller": True,
        "page_count": 52,
        "version": "1.0",
        "author": "GBI Research Team",
        "sector_name": "Technology & IT",
        "business_name": "Software Development Agency",
        "status": "published"
    },
    {
        "title": "Vegetable Gardening",
        "subtitle": "Commercial Production Guide",
        "short_description": "Complete guide to commercial vegetable production in The Gambia.",
        "description": "This report covers crop selection, irrigation methods, pest management, harvesting, and marketing for vegetable farmers.",
        "report_type": "business",
        "format": "pdf",
        "price": 399,
        "is_free": False,
        "is_featured": False,
        "is_bestseller": False,
        "page_count": 42,
        "version": "1.0",
        "author": "GBI Research Team",
        "sector_name": "Agriculture",
        "business_name": "Vegetable Gardening",
        "status": "published"
    },
    {
        "title": "Real Estate Agency",
        "subtitle": "Complete Business Guide",
        "short_description": "Guide to starting a real estate agency in The Gambia's growing property market.",
        "description": "This report covers licensing requirements, commission structures, property marketing, client management, and growth strategies.",
        "report_type": "business",
        "format": "pdf",
        "price": 599,
        "is_free": False,
        "is_featured": True,
        "is_bestseller": False,
        "page_count": 48,
        "version": "1.0",
        "author": "GBI Research Team",
        "sector_name": "Real Estate & Construction",
        "business_name": "Real Estate Agency",
        "status": "published"
    },
    {
        "title": "Fishing Business",
        "subtitle": "Commercial Fishing Guide",
        "short_description": "Complete guide to commercial fishing and fish processing in The Gambia.",
        "description": "This report covers fishing methods, equipment requirements, processing techniques, and export opportunities for the fishing industry.",
        "report_type": "business",
        "format": "pdf",
        "price": 449,
        "is_free": False,
        "is_featured": False,
        "is_bestseller": False,
        "page_count": 44,
        "version": "1.0",
        "author": "GBI Research Team",
        "sector_name": "Agriculture",
        "business_name": "Fishing Business",
        "status": "published"
    },
    {
        "title": "Solar Installation",
        "subtitle": "Renewable Energy Business Guide",
        "short_description": "Guide to starting a solar installation business in The Gambia.",
        "description": "This report covers technical training requirements, equipment sourcing, pricing strategies, customer acquisition, and government incentives.",
        "report_type": "business",
        "format": "pdf",
        "price": 549,
        "is_free": False,
        "is_featured": True,
        "is_bestseller": False,
        "page_count": 46,
        "version": "1.0",
        "author": "GBI Research Team",
        "sector_name": "Renewable Energy",
        "business_name": "Solar Installation",
        "status": "published"
    }
]