# Generated by Django 4.2.7 on 2026-05-17 07:09

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(error_messages={'unique': 'A user with this email already exists.'}, help_text='Email address used for login and notifications.', max_length=255, unique=True, validators=[django.core.validators.EmailValidator()])),
                ('first_name', models.CharField(blank=True, help_text="User's first name.", max_length=100)),
                ('last_name', models.CharField(blank=True, help_text="User's last name.", max_length=100)),
                ('phone', models.CharField(blank=True, help_text='Contact phone number.', max_length=20)),
                ('location', models.CharField(blank=True, help_text='City or region where the user is based.', max_length=200)),
                ('bio', models.TextField(blank=True, help_text='Short bio or professional background.')),
                ('is_entrepreneur', models.BooleanField(default=False, help_text='User identifies as an entrepreneur.')),
                ('is_investor', models.BooleanField(default=False, help_text='User identifies as an investor (local or diaspora).')),
                ('is_student', models.BooleanField(default=False, help_text='User is a student learning about business.')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active.')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, help_text='Date and time when the user registered.')),
                ('last_login_ip', models.GenericIPAddressField(blank=True, help_text='IP address of the last login.', null=True)),
                ('tier', models.CharField(choices=[('regular', 'Regular (Free)'), ('premium', 'Premium (Subscription)'), ('one_time', 'One-Time Purchase')], default='regular', help_text='Access level: Regular (free), Premium (subscription), One-time Purchase.', max_length=20)),
                ('tier_expires_at', models.DateTimeField(blank=True, help_text='For Premium users, when the subscription expires. Null for Regular or One-time.', null=True)),
                ('newsletter_subscribed', models.BooleanField(default=True, help_text='User has opted in to receive email newsletters.')),
                ('email_notifications', models.BooleanField(default=True, help_text='User wants to receive email notifications.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, help_text='Profile picture/avatar.', null=True, upload_to='avatars/')),
                ('linkedin_url', models.URLField(blank=True, help_text='LinkedIn profile URL.')),
                ('twitter_handle', models.CharField(blank=True, help_text='Twitter/X handle (without @).', max_length=100)),
                ('website_url', models.URLField(blank=True, help_text='Personal or business website.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(help_text='The user this profile belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
                'db_table': 'user_profiles',
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_type', models.CharField(choices=[('regular', 'Regular (Free)'), ('premium', 'Premium (Subscription)'), ('one_time', 'One-Time Purchase')], default='premium', help_text='Type of subscription purchased.', max_length=20)),
                ('amount', models.PositiveIntegerField(help_text='Amount paid in Dalasi (D).')),
                ('duration_days', models.PositiveIntegerField(default=30, help_text='Number of days the subscription covers.')),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Date and time when the subscription started.')),
                ('expires_at', models.DateTimeField(help_text='Date and time when the subscription expires.')),
                ('payment_method', models.CharField(blank=True, help_text='Payment method used (card, mobile money, bank transfer, etc.)', max_length=50)),
                ('transaction_reference', models.CharField(blank=True, help_text='Reference number from payment processor.', max_length=200, null=True, unique=True)),
                ('is_paid', models.BooleanField(default=True, help_text='Whether payment has been confirmed.')),
                ('paid_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Date and time when payment was confirmed.')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this subscription is currently active.')),
                ('cancelled_at', models.DateTimeField(blank=True, help_text='Date and time when subscription was cancelled.', null=True)),
                ('notes', models.TextField(blank=True, help_text='Internal notes about this subscription.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(help_text='User who made the subscription purchase.', on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Subscription',
                'verbose_name_plural': 'Subscriptions',
                'db_table': 'subscriptions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_active'], name='subscriptio_user_id_b63ed6_idx'), models.Index(fields=['expires_at'], name='subscriptio_expires_af5d7e_idx'), models.Index(fields=['transaction_reference'], name='subscriptio_transac_ccd580_idx')],
            },
        ),
        migrations.CreateModel(
            name='OneTimePurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_id', models.PositiveIntegerField(help_text='ID of the purchased report (temporary until reports app exists).')),
                ('report_title', models.CharField(help_text='Title of the purchased report.', max_length=200)),
                ('amount', models.PositiveIntegerField(help_text='Amount paid in Dalasi (D).')),
                ('payment_method', models.CharField(blank=True, help_text='Payment method used.', max_length=50)),
                ('transaction_reference', models.CharField(blank=True, help_text='Reference number from payment processor.', max_length=200, null=True, unique=True)),
                ('is_paid', models.BooleanField(default=True, help_text='Whether payment has been confirmed.')),
                ('purchased_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Date and time of purchase.')),
                ('has_downloaded', models.BooleanField(default=False, help_text='Whether the user has downloaded the report.')),
                ('download_count', models.PositiveIntegerField(default=0, help_text='Number of times the report has been downloaded.')),
                ('last_downloaded_at', models.DateTimeField(blank=True, help_text='Date and time of last download.', null=True)),
                ('notes', models.TextField(blank=True, help_text='Internal notes about this purchase.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(help_text='User who made the purchase.', on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'One-Time Purchase',
                'verbose_name_plural': 'One-Time Purchases',
                'db_table': 'one_time_purchases',
                'ordering': ['-purchased_at'],
                'indexes': [models.Index(fields=['user', 'report_id'], name='one_time_pu_user_id_50ab35_idx'), models.Index(fields=['transaction_reference'], name='one_time_pu_transac_71a2bb_idx')],
                'unique_together': {('user', 'report_id')},
            },
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='users_email_4b85f2_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['tier'], name='users_tier_8aada5_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_active'], name='users_is_acti_847b48_idx'),
        ),
    ]
