# Generated by Django 4.2.7 on 2026-05-29 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='plan_type',
            field=models.CharField(choices=[('regular', 'Regular (Free)'), ('premium', 'Premium (Subscription)'), ('one_time', 'One-Time Purchase'), ('pro', 'Pro'), ('enterprise', 'Enterprise')], default='premium', help_text='Type of subscription purchased.', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='tier',
            field=models.CharField(choices=[('regular', 'Regular (Free)'), ('premium', 'Premium (Subscription)'), ('one_time', 'One-Time Purchase'), ('pro', 'Pro'), ('enterprise', 'Enterprise')], default='regular', help_text='Access level: Regular (free), Premium (subscription), One-time Purchase.', max_length=20),
        ),
    ]
