# Generated by Django 4.2.7 on 2026-06-09 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_is_student_user_is_researcher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_researcher',
            field=models.BooleanField(default=False, help_text='User is a researcher or student learning about business.'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, help_text='Profile picture/avatar.', null=True, upload_to='user/avatars/'),
        ),
    ]
