# Generated by Django 4.2.7 on 2026-05-17 07:58

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sectors', '0001_initial'),
        ('businesses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('title', models.CharField(help_text='Report title', max_length=200)),
                ('subtitle', models.CharField(blank=True, help_text='Report subtitle or tagline', max_length=200)),
                ('description', models.TextField(help_text='Detailed description of the report')),
                ('short_description', models.CharField(blank=True, help_text='Short description for listings and cards', max_length=200)),
                ('cover_image', models.ImageField(blank=True, help_text='Cover image for the report', null=True, upload_to='reports/covers/')),
                ('file', models.FileField(help_text='The actual report file (PDF, Excel, etc.)', upload_to='reports/files/')),
                ('file_size', models.PositiveIntegerField(default=0, help_text='File size in bytes (auto-calculated)')),
                ('report_type', models.CharField(choices=[('industry', 'Industry Report'), ('business', 'Business Report'), ('market', 'Market Analysis'), ('investment', 'Investment Guide'), ('regulatory', 'Regulatory Guide'), ('template', 'Business Template')], default='industry', help_text='Type of report', max_length=20)),
                ('format', models.CharField(choices=[('pdf', 'PDF Document'), ('excel', 'Excel Spreadsheet'), ('word', 'Word Document'), ('bundle', 'Bundle Package')], default='pdf', help_text='File format', max_length=20)),
                ('price', models.PositiveIntegerField(default=0, help_text='Price in Dalasi (0 for free)')),
                ('is_free', models.BooleanField(default=False, help_text='Whether this report is free to download')),
                ('table_of_contents', models.TextField(blank=True, help_text='Table of contents (markdown or HTML)')),
                ('key_highlights', models.TextField(blank=True, help_text='Key highlights and takeaways')),
                ('page_count', models.PositiveSmallIntegerField(default=0, help_text='Number of pages')),
                ('version', models.CharField(default='1.0', help_text='Report version', max_length=10)),
                ('author', models.CharField(default='GBI Research Team', help_text='Author or organization', max_length=100)),
                ('is_featured', models.BooleanField(default=False, help_text='Display on homepage and featured sections')),
                ('is_bestseller', models.BooleanField(default=False, help_text='Mark as bestseller')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', help_text='Publication status', max_length=20)),
                ('published_at', models.DateTimeField(blank=True, help_text='When the report was published', null=True)),
                ('download_count', models.PositiveIntegerField(default=0, help_text='Number of downloads')),
                ('view_count', models.PositiveIntegerField(default=0, help_text='Number of views')),
                ('rating', models.DecimalField(decimal_places=2, default=0, help_text='Average rating (0-5)', max_digits=3)),
                ('review_count', models.PositiveIntegerField(default=0, help_text='Number of reviews')),
                ('meta_title', models.CharField(blank=True, help_text='SEO title (defaults to report title)', max_length=150)),
                ('meta_description', models.CharField(blank=True, help_text='SEO description', max_length=300)),
                ('business', models.ForeignKey(blank=True, help_text='Business this report belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='businesses.business')),
                ('sector', models.ForeignKey(blank=True, help_text='Sector this report belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='sectors.sector')),
            ],
            options={
                'verbose_name': 'Report',
                'verbose_name_plural': 'Reports',
                'db_table': 'reports',
                'ordering': ['-is_featured', '-published_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportBundle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('name', models.CharField(help_text='Bundle name', max_length=200)),
                ('description', models.TextField(help_text='Bundle description')),
                ('price', models.PositiveIntegerField(help_text='Bundle price in Dalasi')),
                ('original_price', models.PositiveIntegerField(help_text='Original total price of individual reports')),
                ('discount_percent', models.DecimalField(decimal_places=2, default=0, help_text='Discount percentage (auto-calculated)', max_digits=5)),
                ('cover_image', models.ImageField(blank=True, help_text='Bundle cover image', null=True, upload_to='reports/bundles/')),
                ('is_featured', models.BooleanField(default=False, help_text='Display on homepage and featured sections')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='published', help_text='Publication status', max_length=20)),
                ('valid_until', models.DateTimeField(blank=True, help_text='Optional expiry date for the bundle', null=True)),
                ('purchase_count', models.PositiveIntegerField(default=0, help_text='Number of times this bundle was purchased')),
                ('reports', models.ManyToManyField(help_text='Reports included in this bundle', related_name='bundles', to='reports.report')),
            ],
            options={
                'verbose_name': 'Report Bundle',
                'verbose_name_plural': 'Report Bundles',
                'db_table': 'report_bundles',
                'ordering': ['-is_featured', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('rating', models.PositiveSmallIntegerField(help_text='Rating from 1 to 5 stars', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('title', models.CharField(help_text='Review title', max_length=200)),
                ('content', models.TextField(help_text='Review content')),
                ('is_verified_purchase', models.BooleanField(default=False, help_text='Whether reviewer purchased the report')),
                ('is_approved', models.BooleanField(default=False, help_text='Whether review is approved for display')),
                ('helpful_count', models.PositiveIntegerField(default=0, help_text='Number of users who found this helpful')),
                ('report', models.ForeignKey(help_text='Report being reviewed', on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='reports.report')),
                ('user', models.ForeignKey(help_text='User who wrote the review', on_delete=django.db.models.deletion.CASCADE, related_name='report_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Report Review',
                'verbose_name_plural': 'Report Reviews',
                'db_table': 'report_reviews',
                'ordering': ['-created_at'],
                'unique_together': {('report', 'user')},
            },
        ),
        migrations.CreateModel(
            name='ReportPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('amount_paid', models.PositiveIntegerField(help_text='Amount paid in Dalasi')),
                ('payment_method', models.CharField(blank=True, help_text='Payment method used', max_length=50)),
                ('transaction_reference', models.CharField(blank=True, help_text='Transaction reference from payment processor', max_length=200, null=True, unique=True)),
                ('is_paid', models.BooleanField(default=True, help_text='Whether payment has been confirmed')),
                ('paid_at', models.DateTimeField(auto_now_add=True, help_text='When payment was made')),
                ('has_downloaded', models.BooleanField(default=False, help_text='Whether user has downloaded the report')),
                ('download_count', models.PositiveIntegerField(default=0, help_text='Number of times downloaded')),
                ('last_downloaded_at', models.DateTimeField(blank=True, help_text='Last download timestamp', null=True)),
                ('is_bundle', models.BooleanField(default=False, help_text='Whether this is part of a bundle purchase')),
                ('bundle_reference', models.CharField(blank=True, help_text='Reference for bundle purchases', max_length=100)),
                ('report', models.ForeignKey(help_text='Report that was purchased', on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='reports.report')),
                ('user', models.ForeignKey(help_text='User who purchased the report', on_delete=django.db.models.deletion.CASCADE, related_name='report_purchases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Report Purchase',
                'verbose_name_plural': 'Report Purchases',
                'db_table': 'report_purchases',
                'ordering': ['-paid_at'],
                'indexes': [models.Index(fields=['user', 'report'], name='report_purc_user_id_b60c63_idx'), models.Index(fields=['transaction_reference'], name='report_purc_transac_45a512_idx'), models.Index(fields=['is_paid'], name='report_purc_is_paid_9f0eae_idx')],
                'unique_together': {('user', 'report')},
            },
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['slug'], name='reports_slug_f81d0e_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['status', 'published_at'], name='reports_status_c2688b_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['is_featured'], name='reports_is_feat_fc7e7b_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['report_type'], name='reports_report__ff8b25_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['sector'], name='reports_sector__4a5313_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['business'], name='reports_busines_792cd8_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['download_count'], name='reports_downloa_0e2f79_idx'),
        ),
    ]
