# Generated by Django 4.2.7 on 2026-05-20 19:28

import apps.reports.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='cover_image',
            field=models.ImageField(blank=True, help_text='Cover image for the report', null=True, upload_to=apps.reports.models.report_cover_path),
        ),
        migrations.AlterField(
            model_name='report',
            name='file',
            field=models.FileField(help_text='The actual report file (PDF, Excel, etc.)', upload_to=apps.reports.models.report_file_path),
        ),
    ]
