# Generated by Django 4.2.7 on 2026-05-17 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('name', models.CharField(help_text='Sector name (e.g., Agriculture, Transportation)', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Detailed description of the sector')),
                ('icon', models.CharField(blank=True, help_text="Icon name from Lucide React (e.g., 'Truck', 'Leaf')", max_length=50)),
                ('color', models.CharField(blank=True, help_text="Color code for the sector (e.g., 'blue', 'green')", max_length=20)),
                ('featured_image', models.ImageField(blank=True, help_text='Featured image for the sector', null=True, upload_to='sectors/')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order on the website')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='published', help_text='Publication status', max_length=20)),
                ('business_count', models.PositiveIntegerField(default=0, help_text='Number of businesses in this sector (automatically updated)')),
            ],
            options={
                'verbose_name': 'Sector',
                'verbose_name_plural': 'Sectors',
                'db_table': 'sectors',
                'ordering': ['order', 'name'],
                'indexes': [models.Index(fields=['slug'], name='sectors_slug_c90d4b_idx'), models.Index(fields=['status'], name='sectors_status_1de8a8_idx'), models.Index(fields=['order'], name='sectors_order_fc8627_idx')],
            },
        ),
    ]
