# Generated by Django 4.2.7 on 2026-05-25 10:38

import apps.sectors.models
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="Sector name, e.g. 'Agriculture', 'Transportation'", max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='What this sector covers and why it matters in the Gambian context')),
                ('icon', models.CharField(blank=True, help_text="Lucide React icon name, e.g. 'Truck', 'Leaf', 'ShoppingBag'", max_length=50)),
                ('color', models.CharField(blank=True, help_text="Tailwind colour token or hex, e.g. 'green', '#1D9E75'", max_length=20)),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to=apps.sectors.models.sector_image_path)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order on listing pages (lower = earlier)')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='published', max_length=20)),
                ('business_count', models.PositiveIntegerField(default=0, help_text='Cached count of published businesses in this sector')),
                ('summary_for_ai', models.TextField(blank=True, help_text='Plain-language sector overview written for LLM context injection. Keep to 2–3 sentences. Updated manually when major changes occur.')),
            ],
            options={
                'verbose_name': 'Sector',
                'verbose_name_plural': 'Sectors',
                'db_table': 'sectors',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SectorStat',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(help_text="Human-readable stat name, e.g. 'Estimated market size'", max_length=100)),
                ('value', models.DecimalField(decimal_places=2, help_text='Numeric value (use negative for decreases)', max_digits=20)),
                ('unit', models.CharField(choices=[('D', 'Dalasi (GMD)'), ('%', 'Percentage'), ('number', 'Number'), ('years', 'Years')], default='D', max_length=20)),
                ('display_order', models.PositiveSmallIntegerField(default=0, help_text='Order in which this stat appears on the sector page')),
                ('is_headline', models.BooleanField(default=False, help_text='Show prominently at the top of the sector card')),
                ('year', models.IntegerField(db_index=True, help_text='Year this stat applies to')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Sector stat',
                'verbose_name_plural': 'Sector stats',
                'db_table': 'sector_stats',
                'ordering': ['sector', 'display_order'],
            },
        ),
        migrations.CreateModel(
            name='SectorTag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=60, unique=True)),
                ('slug', models.SlugField(max_length=60, unique=True)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Sector tag',
                'verbose_name_plural': 'Sector tags',
                'db_table': 'sector_tags',
                'ordering': ['label'],
            },
        ),
        migrations.CreateModel(
            name='SectorTagAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Sector tag assignment',
                'verbose_name_plural': 'Sector tag assignments',
                'db_table': 'sector_tag_assignments',
            },
        ),
    ]
