# Generated by Django 4.2.7 on 2026-05-20 19:28

import apps.sectors.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sectors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sector',
            name='featured_image',
            field=models.ImageField(blank=True, help_text='Featured image for the sector', null=True, upload_to=apps.sectors.models.sector_image_path),
        ),
    ]
