# Generated by Django 4.2.7 on 2026-05-25 10:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('sectors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sectortagassignment',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sectortagassignment',
            name='sector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag_assignments', to='sectors.sector'),
        ),
        migrations.AddField(
            model_name='sectortagassignment',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sector_assignments', to='sectors.sectortag'),
        ),
        migrations.AddField(
            model_name='sectorstat',
            name='sector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='sectors.sector'),
        ),
        migrations.AddField(
            model_name='sectorstat',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sector_stats', to='core.source'),
        ),
        migrations.AddField(
            model_name='sector',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Optional parent sector for two-level taxonomy', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='sectors.sector'),
        ),
        migrations.AlterUniqueTogether(
            name='sectortagassignment',
            unique_together={('sector', 'tag')},
        ),
        migrations.AddIndex(
            model_name='sectorstat',
            index=models.Index(fields=['sector', 'year'], name='sector_stat_sector__5274e3_idx'),
        ),
        migrations.AddIndex(
            model_name='sector',
            index=models.Index(fields=['slug'], name='sectors_slug_c90d4b_idx'),
        ),
        migrations.AddIndex(
            model_name='sector',
            index=models.Index(fields=['status'], name='sectors_status_1de8a8_idx'),
        ),
        migrations.AddIndex(
            model_name='sector',
            index=models.Index(fields=['order'], name='sectors_order_fc8627_idx'),
        ),
        migrations.AddIndex(
            model_name='sector',
            index=models.Index(fields=['parent'], name='sectors_parent__448ced_idx'),
        ),
    ]
