# Generated by Django 4.2.7 on 2026-05-28 21:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('sectors', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountryProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('country', models.CharField(choices=[('gm', 'The Gambia'), ('sn', 'Senegal'), ('gw', 'Guinea-Bissau'), ('gn', 'Guinea'), ('ml', 'Mali'), ('ci', "Côte d'Ivoire"), ('bf', 'Burkina Faso'), ('gh', 'Ghana'), ('ng', 'Nigeria'), ('sl', 'Sierra Leone'), ('lr', 'Liberia'), ('bj', 'Benin'), ('tg', 'Togo'), ('cv', 'Cape Verde')], help_text='Country code', max_length=10, unique=True)),
                ('name', models.CharField(help_text='Full country name', max_length=100)),
                ('flag_emoji', models.CharField(blank=True, help_text="Flag emoji (e.g., '🇬🇲')", max_length=10)),
                ('currency', models.CharField(choices=[('GMD', 'Gambian Dalasi'), ('XOF', 'West African CFA Franc'), ('GHS', 'Ghanaian Cedi'), ('NGN', 'Nigerian Naira'), ('USD', 'US Dollar')], default='GMD', help_text='Primary currency', max_length=3)),
                ('currency_symbol', models.CharField(blank=True, help_text="Currency symbol (e.g., 'D', '₦')", max_length=10)),
                ('population', models.PositiveIntegerField(blank=True, help_text='Population estimate', null=True)),
                ('gdp_per_capita', models.DecimalField(blank=True, decimal_places=2, help_text='GDP per capita in USD', max_digits=12, null=True)),
                ('market_summary', models.TextField(blank=True, help_text='Overview of business environment and opportunities')),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='countries/')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether this country is active on the platform')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Country Profile',
                'verbose_name_plural': 'Country Profiles',
                'db_table': 'country_profiles',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AlterModelOptions(
            name='sector',
            options={'ordering': ['country', 'order', 'name'], 'verbose_name': 'Sector', 'verbose_name_plural': 'Sectors'},
        ),
        migrations.AddField(
            model_name='sector',
            name='country',
            field=models.CharField(choices=[('gm', 'The Gambia'), ('sn', 'Senegal'), ('gw', 'Guinea-Bissau'), ('gn', 'Guinea'), ('ml', 'Mali'), ('ci', "Côte d'Ivoire"), ('bf', 'Burkina Faso'), ('gh', 'Ghana'), ('ng', 'Nigeria'), ('sl', 'Sierra Leone'), ('lr', 'Liberia'), ('bj', 'Benin'), ('tg', 'Togo'), ('cv', 'Cape Verde')], db_index=True, default='gm', help_text='Country this sector data applies to', max_length=10),
        ),
        migrations.AddField(
            model_name='sector',
            name='currency',
            field=models.CharField(choices=[('GMD', 'Gambian Dalasi'), ('XOF', 'West African CFA Franc'), ('GHS', 'Ghanaian Cedi'), ('NGN', 'Nigerian Naira'), ('USD', 'US Dollar')], default='GMD', help_text='Default currency for this sector/country', max_length=3),
        ),
        migrations.AddField(
            model_name='sector',
            name='estimated_market_size',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Estimated market size in local currency', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='sector',
            name='estimated_market_size_display',
            field=models.CharField(blank=True, help_text="Formatted market size (e.g., 'D2.4B')", max_length=50),
        ),
        migrations.AddField(
            model_name='sector',
            name='region',
            field=models.CharField(blank=True, choices=[('west_africa', 'West Africa'), ('ecowas', 'ECOWAS'), ('gambia_river', 'Gambia River Basin'), ('coastal', 'Coastal West Africa'), ('sahelian', 'Sahelian West Africa')], db_index=True, help_text='Regional grouping for cross-country analysis', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='sectorstat',
            name='country',
            field=models.CharField(blank=True, choices=[('gm', 'The Gambia'), ('sn', 'Senegal'), ('gw', 'Guinea-Bissau'), ('gn', 'Guinea'), ('ml', 'Mali'), ('ci', "Côte d'Ivoire"), ('bf', 'Burkina Faso'), ('gh', 'Ghana'), ('ng', 'Nigeria'), ('sl', 'Sierra Leone'), ('lr', 'Liberia'), ('bj', 'Benin'), ('tg', 'Togo'), ('cv', 'Cape Verde')], db_index=True, help_text='Country this stat applies to (null = same as sector)', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='sectorstat',
            name='region',
            field=models.CharField(blank=True, choices=[('west_africa', 'West Africa'), ('ecowas', 'ECOWAS'), ('gambia_river', 'Gambia River Basin'), ('coastal', 'Coastal West Africa'), ('sahelian', 'Sahelian West Africa')], db_index=True, help_text='Region this stat applies to', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='sector',
            name='description',
            field=models.TextField(blank=True, help_text='What this sector covers and why it matters in the local context'),
        ),
        migrations.AlterField(
            model_name='sector',
            name='name',
            field=models.CharField(help_text="Sector name, e.g. 'Agriculture', 'Transportation'", max_length=100),
        ),
        migrations.AlterField(
            model_name='sectorstat',
            name='unit',
            field=models.CharField(choices=[('D', 'Dalasi (GMD)'), ('XOF', 'CFA Franc'), ('GHS', 'Ghana Cedi'), ('NGN', 'Naira'), ('USD', 'US Dollar'), ('%', 'Percentage'), ('number', 'Number'), ('years', 'Years')], default='D', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='sector',
            unique_together={('name', 'country')},
        ),
        migrations.AddIndex(
            model_name='sector',
            index=models.Index(fields=['country', 'status'], name='sectors_country_c063ff_idx'),
        ),
        migrations.AddIndex(
            model_name='sector',
            index=models.Index(fields=['region', 'status'], name='sectors_region_85c21a_idx'),
        ),
        migrations.AddIndex(
            model_name='sector',
            index=models.Index(fields=['country', 'parent'], name='sectors_country_09b2ff_idx'),
        ),
        migrations.AddIndex(
            model_name='sectorstat',
            index=models.Index(fields=['country', 'year'], name='sector_stat_country_199f63_idx'),
        ),
        migrations.AddIndex(
            model_name='sectorstat',
            index=models.Index(fields=['region', 'year'], name='sector_stat_region_d5e37c_idx'),
        ),
    ]
