# Generated by Django 4.2.7 on 2026-05-29 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sectors', '0003_countryprofile_alter_sector_options_sector_country_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CountryProfile',
        ),
        migrations.AlterField(
            model_name='sector',
            name='country',
            field=models.CharField(choices=[('gm', 'The Gambia'), ('sn', 'Senegal'), ('gh', 'Ghana'), ('ng', 'Nigeria'), ('ci', "Côte d'Ivoire"), ('ml', 'Mali'), ('bf', 'Burkina Faso'), ('gn', 'Guinea'), ('gw', 'Guinea-Bissau'), ('sl', 'Sierra Leone'), ('lr', 'Liberia'), ('bj', 'Benin'), ('tg', 'Togo'), ('cv', 'Cape Verde'), ('ne', 'Niger'), ('mr', 'Mauritania')], db_index=True, default='gm', help_text='Country this sector data applies to', max_length=2),
        ),
        migrations.AlterField(
            model_name='sector',
            name='currency',
            field=models.CharField(choices=[('GMD', 'Gambian Dalasi'), ('XOF', 'West African CFA Franc'), ('GHS', 'Ghanaian Cedi'), ('NGN', 'Nigerian Naira'), ('USD', 'US Dollar'), ('GNF', 'Guinean Franc'), ('SLL', 'Sierra Leonean Leone'), ('LRD', 'Liberian Dollar'), ('CVE', 'Cape Verdean Escudo'), ('MRU', 'Mauritanian Ouguiya')], default='GMD', help_text='Default currency for this sector/country', max_length=3),
        ),
        migrations.AlterField(
            model_name='sector',
            name='region',
            field=models.CharField(blank=True, choices=[('west_africa', 'West Africa'), ('ecowas', 'ECOWAS (Economic Community of West African States)'), ('coastal', 'Coastal West Africa'), ('sahelian', 'Sahelian West Africa'), ('gambia_river', 'Gambia River Basin'), ('francophone', 'Francophone West Africa'), ('anglophone', 'Anglophone West Africa')], db_index=True, help_text='Regional grouping for cross-country analysis', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='sector',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('review', 'Under Review'), ('published', 'Published'), ('archived', 'Archived')], db_index=True, default='published', max_length=20),
        ),
        migrations.AlterField(
            model_name='sectorstat',
            name='country',
            field=models.CharField(blank=True, choices=[('gm', 'The Gambia'), ('sn', 'Senegal'), ('gh', 'Ghana'), ('ng', 'Nigeria'), ('ci', "Côte d'Ivoire"), ('ml', 'Mali'), ('bf', 'Burkina Faso'), ('gn', 'Guinea'), ('gw', 'Guinea-Bissau'), ('sl', 'Sierra Leone'), ('lr', 'Liberia'), ('bj', 'Benin'), ('tg', 'Togo'), ('cv', 'Cape Verde'), ('ne', 'Niger'), ('mr', 'Mauritania')], db_index=True, help_text='Country this stat applies to (null = same as sector)', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='sectorstat',
            name='region',
            field=models.CharField(blank=True, choices=[('west_africa', 'West Africa'), ('ecowas', 'ECOWAS (Economic Community of West African States)'), ('coastal', 'Coastal West Africa'), ('sahelian', 'Sahelian West Africa'), ('gambia_river', 'Gambia River Basin'), ('francophone', 'Francophone West Africa'), ('anglophone', 'Anglophone West Africa')], db_index=True, help_text='Region this stat applies to', max_length=30, null=True),
        ),
    ]
